build:
  image: default-bionic
  environment:
    php:
      version: "8.3.1"
      ini:
        memory_limit: "-1"
      pecl_extensions:
        - redis
    redis: true
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: ./bin/doctrine orm:generate-proxies && XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover build/coverage-clover.xml tests
            coverage:
              file: build/coverage-clover.xml
              format: clover
filter:
  paths:
    - 'src/'
  excluded_paths:
    - 'src/html/'
    - 'src/OrmProxy/'
    - 'src/Public/assets/'
  dependency_paths:
    - 'vendor/'
checks:
  php:
    code_rating: true
