build:
  image: default-jammy
  environment:
    php:
      version: "8.4.11"
      ini:
        memory_limit: "-1"
        xdebug.mode: coverage
      pecl_extensions:
        - redis
    redis: true
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover build/coverage-clover.xml tests
            coverage:
              file: build/coverage-clover.xml
              format: clover
filter:
  paths:
    - 'src/'
  excluded_paths:
    - 'src/html/'
    - 'src/Migrations/'
    - 'src/OrmProxy/'
    - 'src/Public/assets/'
  dependency_paths:
    - 'vendor/'
checks:
  php:
    code_rating: true
build_failure_conditions:
  - 'elements.rating(<= D).exists'               # No classes/methods with a rating of D or worse
#  - 'project.metric_change("scrutinizer.test_coverage", < -0.10)'  # Code Coverage decreased from previous inspection by more than 10%
