build:
  image: default-bionic
  environment:
    php:
      version: "8.3.1"
      ini:
        memory_limit: "-1"
      pecl_extensions:
        - redis
    redis: true
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover build/coverage-clover.xml tests
            coverage:
              file: build/coverage-clover.xml
              format: clover
filter:
  paths:
    - 'src/'
checks:
  php:
    code_rating: true
tools:
  php_mess_detector:
    enabled: true
    filter:
      paths:
        - 'src/'
  php_code_sniffer:
    enabled: false
  php_pdepend:
    enabled: true
    configuration_file: null
    suffixes:
      - php
    excluded_dirs: {  }
    filter:
      paths:
        - 'src/'
  php_analyzer:
    enabled: true
    extensions:
      - php
    filter:
      paths:
        - 'src/'
    path_configs: {  }
  php_loc:
    enabled: true
    excluded_dirs:
      - 'vendor/*'
      - 'tests/*'
      - '.phpstorm.meta.php'
  php_cpd:
    enabled: true
    excluded_dirs: {  }
    filter:
      paths:
        - 'src/'
