<?php

declare(strict_types=1);

namespace Stu\Component\Crew\Skill;

enum SkillEnhancementEnum: int
{
    case REACH_ASTRO_WAYPOINT = 1;
    case FINISH_ASTRO_MAPPING = 2;
    case SPACECRAFT_DESTRUCTION = 3;
    case SPACECRAFT_TAKEOVER = 4;
    case SALVAGE_EMERGENCY_PODS = 5;
    case REPAIR_COMPLETED = 6;
    case FOREIGN_SPACECRAFT_SCAN = 7;
    case EVADE_ATTACK = 8;
    case ESCAPE_TRACTOR_BEAM = 9;
    case FOREIGN_CONTACT_MESSAGE = 10;
    case ACTIVATE_TRACTOR_BEAM = 11;
    case SET_ALERT_YELLOW_OR_RED = 12;
    case DECLOAK_FOREIGN_SPACECRAFT = 13;
    case ION_STORM_FLIGHT = 14;
    case FOREIGN_COLONY_SCAN = 15;
    case START_FOREIGN_SUBSPACE_ANALYSIS = 16;
    case SUBSPACE_ELLIPSE_TICK = 17;
    case ATTACK_FOREIGN_COLONY = 18;
    case CONSTRUCTION_CREATED = 19;
    case BEAM_COMMODITIES = 20;
    case WARP_FLIGHT_WITHOUT_DEFLECTOR_ENERGY = 21;
    case MAINTENANCE_TICK = 22;
}
