<?php

declare(strict_types=1);

namespace Stu\Component\Building;

enum BuildingFunctionEnum: int
{
        // building functions
    case BUILDING_FUNCTION_COLONY_CENTRAL = 1;
    case BUILDING_FUNCTION_BASE_CAMP = 2;
    case BUILDING_FUNCTION_AIRFIELD = 4;
    case BUILDING_FUNCTION_FIGHTER_SHIPYARD = 5;
    case BUILDING_FUNCTION_ESCORT_SHIPYARD = 6;
    case BUILDING_FUNCTION_FRIGATE_SHIPYARD = 7;
    case BUILDING_FUNCTION_CRUISER_SHIPYARD = 8;
    case BUILDING_FUNCTION_TORPEDO_FAB = 9;
    case BUILDING_FUNCTION_MODULEFAB_TYPE1_LVL1 = 10;
    case BUILDING_FUNCTION_MODULEFAB_TYPE1_LVL2 = 11;
    case BUILDING_FUNCTION_MODULEFAB_TYPE1_LVL3 = 12;
    case BUILDING_FUNCTION_MODULEFAB_TYPE2_LVL1 = 13;
    case BUILDING_FUNCTION_MODULEFAB_TYPE2_LVL2 = 14;
    case BUILDING_FUNCTION_MODULEFAB_TYPE2_LVL3 = 15;
    case BUILDING_FUNCTION_MODULEFAB_TYPE3_LVL1 = 16;
    case BUILDING_FUNCTION_MODULEFAB_TYPE3_LVL2 = 17;
    case BUILDING_FUNCTION_MODULEFAB_TYPE3_LVL3 = 18;
    case BUILDING_FUNCTION_ACADEMY = 20;
    case BUILDING_FUNCTION_DESTROYER_SHIPYARD = 21;
    case BUILDING_FUNCTION_REPAIR_SHIPYARD = 22;
    case BUILDING_FUNCTION_WAREHOUSE = 23;
    case BUILDING_FUNCTION_SUBSPACE_TELESCOPE = 31;

        // planetary defense
    case BUILDING_FUNCTION_SHIELD_GENERATOR = 24;
    case BUILDING_FUNCTION_SHIELD_BATTERY = 25;
    case BUILDING_FUNCTION_ENERGY_PHALANX = 26;
    case BUILDING_FUNCTION_PARTICLE_PHALANX = 27;
    case BUILDING_FUNCTION_ANTI_PARTICLE = 28;

        // spare parts
    case BUILDING_FUNCTION_FABRICATION_HALL = 29;
    case BUILDING_FUNCTION_TECH_CENTER = 30;
}
