<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250623081902_RumpModuleLevels extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add values column for cleaner implementation.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            DROP INDEX rump_module_level_ship_rump_idx
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rumps_module_level DROP CONSTRAINT idx_223131_primary
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rumps_module_level RENAME TO stu_rump_module_level
        SQL);

        //migrate data
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD type_values JSON DEFAULT NULL
        SQL);
        $this->fillValues();


        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD CONSTRAINT FK_83E895DE2EE98D4C FOREIGN KEY (rump_id) REFERENCES stu_rump (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD PRIMARY KEY (rump_id)
        SQL);

        $this->removeObsoleteFields();
    }

    private function fillValues(): void
    {
        $this->addSql(<<<'SQL'
            UPDATE stu_rump_module_level AS s
            SET type_values = level_json
            FROM (
                SELECT rump_id, jsonb_object_agg(level::text, jsonb_build_object(
                    'min', min_val,
                    'default', def_val,
                    'max', max_val,
                    'mandatory', (mandatory != 0)
                )) AS level_json
                FROM (
                    SELECT rump_id, 1 AS level, module_level_1_min AS min_val, module_level_1 AS def_val, module_level_1_max AS max_val, module_mandatory_1 AS mandatory FROM stu_rump_module_level
                    UNION ALL
                    SELECT rump_id, 2, module_level_2_min, module_level_2, module_level_2_max, module_mandatory_2 FROM stu_rump_module_level
                    UNION ALL
                    SELECT rump_id, 3, module_level_3_min, module_level_3, module_level_3_max, module_mandatory_3 FROM stu_rump_module_level
                    UNION ALL
                    SELECT rump_id, 4, module_level_4_min, module_level_4, module_level_4_max, module_mandatory_4 FROM stu_rump_module_level
                    UNION ALL
                    SELECT rump_id, 5, module_level_5_min, module_level_5, module_level_5_max, module_mandatory_5 FROM stu_rump_module_level
                    UNION ALL
                    SELECT rump_id, 6, module_level_6_min, module_level_6, module_level_6_max, module_mandatory_6 FROM stu_rump_module_level
                    UNION ALL
                    SELECT rump_id, 7, module_level_7_min, module_level_7, module_level_7_max, module_mandatory_7 FROM stu_rump_module_level
                    UNION ALL
                    SELECT rump_id, 8, module_level_8_min, module_level_8, module_level_8_max, module_mandatory_8 FROM stu_rump_module_level
                    UNION ALL
                    SELECT rump_id, 10, module_level_10_min, module_level_10, module_level_10_max, module_mandatory_10 FROM stu_rump_module_level
                    UNION ALL
                    SELECT rump_id, 11, module_level_11_min, module_level_11, module_level_11_max, module_mandatory_11 FROM stu_rump_module_level
                ) AS levels
                GROUP BY rump_id
            ) AS json_data
            WHERE s.rump_id = json_data.rump_id;
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->recreateRemovedColumns();

        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP CONSTRAINT FK_83E895DE2EE98D4C
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP CONSTRAINT stu_rump_module_level_pkey
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level RENAME TO stu_rumps_module_level
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rumps_module_level ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rumps_module_level DROP type_values
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX rump_module_level_ship_rump_idx ON stu_rumps_module_level (rump_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rumps_module_level ADD CONSTRAINT idx_223131_primary PRIMARY KEY (id)
        SQL);
    }

    private function removeObsoleteFields(): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_1
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_2
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_3
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_4
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_5
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_7
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_8
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_mandatory_1
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_mandatory_2
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_mandatory_3
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_mandatory_4
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_mandatory_5
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_mandatory_6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_mandatory_7
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_mandatory_8
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_1_min
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_1_max
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_2_min
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_2_max
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_3_min
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_3_max
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_4_min
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_4_max
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_5_min
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_5_max
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_6_min
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_6_max
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_7_min
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_7_max
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_8_min
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_8_max
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_11
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_mandatory_11
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_11_min
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_11_max
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_10
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_mandatory_10
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_10_min
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level DROP module_level_10_max
        SQL);
    }


    private function recreateRemovedColumns(): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_1 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_2 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_3 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_4 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_5 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_6 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_7 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_8 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_mandatory_1 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_mandatory_2 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_mandatory_3 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_mandatory_4 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_mandatory_5 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_mandatory_6 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_mandatory_7 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_mandatory_8 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_1_min SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_1_max SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_2_min SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_2_max SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_3_min SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_3_max SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_4_min SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_4_max SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_5_min SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_5_max SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_6_min SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_6_max SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_7_min SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_7_max SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_8_min SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_8_max SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_11 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_mandatory_11 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_11_min SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_11_max SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_10 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_mandatory_10 SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_10_min SMALLINT NOT NULL DEFAULT 0
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_rump_module_level ADD module_level_10_max SMALLINT NOT NULL DEFAULT 0
        SQL);
    }
}
