<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251022170056 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stu_alliance_applications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date INT NOT NULL, alliance_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E317119C10A0EA3F ON stu_alliance_applications (alliance_id)');
        $this->addSql('CREATE INDEX IDX_E317119CA76ED395 ON stu_alliance_applications (user_id)');
        $this->addSql('CREATE TABLE stu_alliance_member_job (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, job_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_81B01F0FA76ED395 ON stu_alliance_member_job (user_id)');
        $this->addSql('CREATE INDEX IDX_81B01F0FBE04EA9 ON stu_alliance_member_job (job_id)');
        $this->addSql('ALTER TABLE stu_alliance_applications ADD CONSTRAINT FK_E317119C10A0EA3F FOREIGN KEY (alliance_id) REFERENCES stu_alliances (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_alliance_applications ADD CONSTRAINT FK_E317119CA76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_alliance_member_job ADD CONSTRAINT FK_81B01F0FA76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_alliance_member_job ADD CONSTRAINT FK_81B01F0FBE04EA9 FOREIGN KEY (job_id) REFERENCES stu_alliances_jobs (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_alliances_jobs DROP CONSTRAINT fk_3c71c67ba76ed395');
        $this->addSql('DROP INDEX idx_3c71c67ba76ed395');
        $this->addSql('ALTER TABLE stu_alliances_jobs ADD title VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE stu_alliances_jobs ADD sort INT DEFAULT NULL');
        $this->addSql('ALTER TABLE stu_alliances_jobs ADD is_founder_permission BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE stu_alliances_jobs ADD is_successor_permission BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE stu_alliances_jobs ADD is_diplomatic_permission BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE stu_alliances_jobs ALTER user_id DROP NOT NULL');
        $this->addSql('ALTER TABLE stu_alliances_jobs ALTER type DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stu_alliance_applications DROP CONSTRAINT FK_E317119C10A0EA3F');
        $this->addSql('ALTER TABLE stu_alliance_applications DROP CONSTRAINT FK_E317119CA76ED395');
        $this->addSql('ALTER TABLE stu_alliance_member_job DROP CONSTRAINT FK_81B01F0FA76ED395');
        $this->addSql('ALTER TABLE stu_alliance_member_job DROP CONSTRAINT FK_81B01F0FBE04EA9');
        $this->addSql('DROP TABLE stu_alliance_applications');
        $this->addSql('DROP TABLE stu_alliance_member_job');
        $this->addSql('ALTER TABLE stu_alliances_jobs DROP title');
        $this->addSql('ALTER TABLE stu_alliances_jobs DROP sort');
        $this->addSql('ALTER TABLE stu_alliances_jobs DROP is_founder_permission');
        $this->addSql('ALTER TABLE stu_alliances_jobs DROP is_successor_permission');
        $this->addSql('ALTER TABLE stu_alliances_jobs DROP is_diplomatic_permission');
        $this->addSql('ALTER TABLE stu_alliances_jobs ALTER user_id SET NOT NULL');
        $this->addSql('ALTER TABLE stu_alliances_jobs ALTER type SET NOT NULL');
        $this->addSql('ALTER TABLE stu_alliances_jobs ADD CONSTRAINT fk_3c71c67ba76ed395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON UPDATE RESTRICT ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_3c71c67ba76ed395 ON stu_alliances_jobs (user_id)');
    }
}
