<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;


final class Version20241203174248_WormholeRestrictions extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Wormhole Restrictions';
    }

    public function up(Schema $schema): void
    {

        $this->addSql('CREATE TABLE stu_wormhole_restrictions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mode INT DEFAULT NULL, wormhole_entry_id INT DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_76C7B8E0BE56147A ON stu_wormhole_restrictions (wormhole_entry_id)');
        $this->addSql('CREATE INDEX IDX_76C7B8E0A76ED395 ON stu_wormhole_restrictions (user_id)');
        $this->addSql('ALTER TABLE stu_wormhole_restrictions ADD CONSTRAINT FK_76C7B8E0BE56147A FOREIGN KEY (wormhole_entry_id) REFERENCES stu_wormhole_entry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_wormhole_restrictions ADD CONSTRAINT FK_76C7B8E0A76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {

        $this->addSql('ALTER TABLE stu_wormhole_restrictions DROP CONSTRAINT FK_76C7B8E0BE56147A');
        $this->addSql('ALTER TABLE stu_wormhole_restrictions DROP CONSTRAINT FK_76C7B8E0A76ED395');
        $this->addSql('DROP TABLE stu_wormhole_restrictions');
    }
}
