<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250114095354_Enhancement_Log extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Introduce skill enhancement log entity.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE stu_skill_enhancement_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, enhancement_id INT NOT NULL, crew_name VARCHAR(255) NOT NULL, promotion VARCHAR(255) DEFAULT NULL, ship_name VARCHAR(255) NOT NULL, expertise INT NOT NULL, expertise_sum INT NOT NULL, date INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_73B42DBBA76ED395 ON stu_skill_enhancement_log (user_id)');
        $this->addSql('CREATE INDEX IDX_73B42DBB49186B17 ON stu_skill_enhancement_log (enhancement_id)');
        $this->addSql('ALTER TABLE stu_skill_enhancement_log ADD CONSTRAINT FK_73B42DBBA76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_skill_enhancement_log ADD CONSTRAINT FK_73B42DBB49186B17 FOREIGN KEY (enhancement_id) REFERENCES stu_skill_enhancement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE stu_skill_enhancement_log DROP CONSTRAINT FK_73B42DBBA76ED395');
        $this->addSql('ALTER TABLE stu_skill_enhancement_log DROP CONSTRAINT FK_73B42DBB49186B17');
        $this->addSql('DROP TABLE stu_skill_enhancement_log');
    }
}
