<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250627070640 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remove obsolete entity.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_user_tag DROP CONSTRAINT fk_56cc7d00a76ed395
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE stu_user_tag
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE stu_user_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, tag_type_id INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_56cc7d00a76ed395 ON stu_user_tag (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_user_tag ADD CONSTRAINT fk_56cc7d00a76ed395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON UPDATE RESTRICT ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }
}
