<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260801191411 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds crew skills, ranks and their enhancement log.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE stu_crew ADD rank VARCHAR(255) DEFAULT 'RECRUIT' NOT NULL");

        $this->addSql('CREATE TABLE stu_crew_skill (crew_id INT NOT NULL, position SMALLINT NOT NULL, expertise INT NOT NULL, PRIMARY KEY(crew_id, position))');
        $this->addSql('CREATE INDEX IDX_5AD19B5F5FE259F6 ON stu_crew_skill (crew_id)');
        $this->addSql('ALTER TABLE stu_crew_skill ADD CONSTRAINT FK_5AD19B5F5FE259F6 FOREIGN KEY (crew_id) REFERENCES stu_crew (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE stu_skill_enhancement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type SMALLINT NOT NULL, position SMALLINT NOT NULL, expertise INT NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX skill_enhancement_unique_idx ON stu_skill_enhancement (type, position)');

        $this->addSql('CREATE TABLE stu_skill_enhancement_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, enhancement_id INT NOT NULL, crew_id INT NOT NULL, crew_name VARCHAR(255) NOT NULL, promotion VARCHAR(255) DEFAULT NULL, ship_name VARCHAR(255) NOT NULL, expertise INT NOT NULL, expertise_sum INT NOT NULL, date INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_73B42DBBA76ED395 ON stu_skill_enhancement_log (user_id)');
        $this->addSql('CREATE INDEX IDX_73B42DBB49186B17 ON stu_skill_enhancement_log (enhancement_id)');
        $this->addSql('ALTER TABLE stu_skill_enhancement_log ADD CONSTRAINT FK_73B42DBBA76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_skill_enhancement_log ADD CONSTRAINT FK_73B42DBB49186B17 FOREIGN KEY (enhancement_id) REFERENCES stu_skill_enhancement (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE stu_skill_enhancement_log DROP CONSTRAINT FK_73B42DBBA76ED395');
        $this->addSql('ALTER TABLE stu_skill_enhancement_log DROP CONSTRAINT FK_73B42DBB49186B17');
        $this->addSql('DROP TABLE stu_skill_enhancement_log');
        $this->addSql('DROP TABLE stu_skill_enhancement');
        $this->addSql('ALTER TABLE stu_crew_skill DROP CONSTRAINT FK_5AD19B5F5FE259F6');
        $this->addSql('DROP TABLE stu_crew_skill');
        $this->addSql('ALTER TABLE stu_crew DROP rank');
    }
}
