<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;


final class Version20240806141232 extends AbstractMigration
{
    #[\Override]
    public function getDescription(): string
    {
        return 'Add mining queue entity';
    }

    #[\Override]
    public function up(Schema $schema): void
    {

        $this->addSql('CREATE TABLE stu_mining_queue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ship_id INT NOT NULL, location_mining_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BBFEF8C427D56C25 ON stu_mining_queue (location_mining_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BBFEF8C4C256317D ON stu_mining_queue (ship_id)');
        $this->addSql('ALTER TABLE stu_mining_queue ADD CONSTRAINT FK_BBFEF8C427D56C25 FOREIGN KEY (location_mining_id) REFERENCES stu_location_mining (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_mining_queue ADD CONSTRAINT FK_BBFEF8C4C256317D FOREIGN KEY (ship_id) REFERENCES stu_ships (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    #[\Override]
    public function down(Schema $schema): void
    {
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE stu_mining_queue DROP CONSTRAINT FK_BBFEF8C427D56C25');
        $this->addSql('ALTER TABLE stu_mining_queue DROP CONSTRAINT FK_BBFEF8C4C256317D');
        $this->addSql('DROP TABLE stu_mining_queue');
    }
}
