<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251102185756 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stu_npc_quest_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quest_id INT NOT NULL, user_id INT NOT NULL, text TEXT NOT NULL, date INT NOT NULL, deleted INT DEFAULT NULL, mode INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX npc_quest_log_quest_idx ON stu_npc_quest_log (quest_id)');
        $this->addSql('CREATE INDEX npc_quest_log_user_idx ON stu_npc_quest_log (user_id)');
        $this->addSql('CREATE TABLE stu_npc_quest_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quest_id INT NOT NULL, user_id INT NOT NULL, mode INT NOT NULL, reward_received BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX npc_quest_user_quest_idx ON stu_npc_quest_user (quest_id)');
        $this->addSql('CREATE INDEX npc_quest_user_user_idx ON stu_npc_quest_user (user_id)');
        $this->addSql('CREATE TABLE stu_npc_quests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, title TEXT NOT NULL, text TEXT NOT NULL, factions JSON DEFAULT NULL, prestige INT DEFAULT NULL, commodity_reward JSON DEFAULT NULL, spacecrafts JSON DEFAULT NULL, award_id INT DEFAULT NULL, time INT NOT NULL, start INT NOT NULL, application_end INT NOT NULL, "end" INT DEFAULT NULL, secret JSON DEFAULT NULL, approval_required BOOLEAN NOT NULL, applicant_max INT DEFAULT NULL, plot_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX npc_quest_user_idx ON stu_npc_quests (user_id)');
        $this->addSql('CREATE INDEX npc_quest_award_idx ON stu_npc_quests (award_id)');
        $this->addSql('CREATE INDEX npc_quest_plot_idx ON stu_npc_quests (plot_id)');
        $this->addSql('ALTER TABLE stu_npc_quest_log ADD CONSTRAINT FK_58B6461D209E9EF4 FOREIGN KEY (quest_id) REFERENCES stu_npc_quests (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_npc_quest_log ADD CONSTRAINT FK_58B6461DA76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_npc_quest_user ADD CONSTRAINT FK_54C0581209E9EF4 FOREIGN KEY (quest_id) REFERENCES stu_npc_quests (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_npc_quests ADD CONSTRAINT FK_F77F13CAA76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_npc_quests ADD CONSTRAINT FK_F77F13CA3D5282CF FOREIGN KEY (award_id) REFERENCES stu_award (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_npc_quests ADD CONSTRAINT FK_F77F13CA680D0B01 FOREIGN KEY (plot_id) REFERENCES stu_plots (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stu_npc_quest_log DROP CONSTRAINT FK_58B6461D209E9EF4');
        $this->addSql('ALTER TABLE stu_npc_quest_log DROP CONSTRAINT FK_58B6461DA76ED395');
        $this->addSql('ALTER TABLE stu_npc_quest_user DROP CONSTRAINT FK_54C0581209E9EF4');
        $this->addSql('ALTER TABLE stu_npc_quests DROP CONSTRAINT FK_F77F13CAA76ED395');
        $this->addSql('ALTER TABLE stu_npc_quests DROP CONSTRAINT FK_F77F13CA3D5282CF');
        $this->addSql('ALTER TABLE stu_npc_quests DROP CONSTRAINT FK_F77F13CA680D0B01');
        $this->addSql('DROP TABLE stu_npc_quest_log');
        $this->addSql('DROP TABLE stu_npc_quest_user');
        $this->addSql('DROP TABLE stu_npc_quests');
    }
}
