<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;


final class Version20250416113049_Colony_Class_Restriction extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add colony class restriction table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE stu_colony_class_restriction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, colony_class_id INT NOT NULL, terraforming_id INT DEFAULT NULL, building_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CEF73D7ABA61CECC ON stu_colony_class_restriction (colony_class_id)');
        $this->addSql('CREATE INDEX IDX_CEF73D7ABD31079C ON stu_colony_class_restriction (terraforming_id)');
        $this->addSql('CREATE INDEX IDX_CEF73D7A4D2A7E12 ON stu_colony_class_restriction (building_id)');
        $this->addSql('ALTER TABLE stu_colony_class_restriction ADD CONSTRAINT FK_CEF73D7ABA61CECC FOREIGN KEY (colony_class_id) REFERENCES stu_colonies_classes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_colony_class_restriction ADD CONSTRAINT FK_CEF73D7ABD31079C FOREIGN KEY (terraforming_id) REFERENCES stu_terraforming (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_colony_class_restriction ADD CONSTRAINT FK_CEF73D7A4D2A7E12 FOREIGN KEY (building_id) REFERENCES stu_buildings (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE stu_colony_class_restriction DROP CONSTRAINT FK_CEF73D7ABA61CECC');
        $this->addSql('ALTER TABLE stu_colony_class_restriction DROP CONSTRAINT FK_CEF73D7ABD31079C');
        $this->addSql('ALTER TABLE stu_colony_class_restriction DROP CONSTRAINT FK_CEF73D7A4D2A7E12');
        $this->addSql('DROP TABLE stu_colony_class_restriction');
    }
}