<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260906134102 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stu_relation_permissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, permission SMALLINT NOT NULL, direction SMALLINT NOT NULL, pending BOOLEAN NOT NULL, granted BOOLEAN NOT NULL, offered_by_source BOOLEAN NOT NULL, relation_id INT DEFAULT NULL, contact_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4FB919C33256915B ON stu_relation_permissions (relation_id)');
        $this->addSql('CREATE INDEX IDX_4FB919C3E7A1254A ON stu_relation_permissions (contact_id)');
        $this->addSql('ALTER TABLE stu_relation_permissions ADD CONSTRAINT FK_4FB919C33256915B FOREIGN KEY (relation_id) REFERENCES stu_relations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_relation_permissions ADD CONSTRAINT FK_4FB919C3E7A1254A FOREIGN KEY (contact_id) REFERENCES stu_contactlist (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_contactlist DROP CONSTRAINT fk_451bb4b0a76ed395');
        $this->addSql('ALTER TABLE stu_contactlist DROP CONSTRAINT fk_451bb4b06804fb49');
        $this->addSql('ALTER TABLE stu_contactlist ADD CONSTRAINT FK_451BB4B0A76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_contactlist ADD CONSTRAINT FK_451BB4B06804FB49 FOREIGN KEY (recipient) REFERENCES stu_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stu_relation_permissions DROP CONSTRAINT FK_4FB919C33256915B');
        $this->addSql('ALTER TABLE stu_relation_permissions DROP CONSTRAINT FK_4FB919C3E7A1254A');
        $this->addSql('DROP TABLE stu_relation_permissions');
        $this->addSql('ALTER TABLE stu_contactlist DROP CONSTRAINT FK_451BB4B0A76ED395');
        $this->addSql('ALTER TABLE stu_contactlist DROP CONSTRAINT FK_451BB4B06804FB49');
        $this->addSql('ALTER TABLE stu_contactlist ADD CONSTRAINT fk_451bb4b0a76ed395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON UPDATE RESTRICT ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_contactlist ADD CONSTRAINT fk_451bb4b06804fb49 FOREIGN KEY (recipient) REFERENCES stu_user (id) ON UPDATE RESTRICT ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
