<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260826065815 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stu_user_relations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type SMALLINT NOT NULL, source_user_id INT DEFAULT NULL, source_alliance_id INT DEFAULT NULL, recipient_user_id INT DEFAULT NULL, recipient_alliance_id INT DEFAULT NULL, date INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX user_relation_source_user_idx ON stu_user_relations (source_user_id)');
        $this->addSql('CREATE INDEX user_relation_recipient_user_idx ON stu_user_relations (recipient_user_id)');
        $this->addSql('CREATE INDEX user_relation_source_alliance_idx ON stu_user_relations (source_alliance_id)');
        $this->addSql('CREATE INDEX user_relation_recipient_alliance_idx ON stu_user_relations (recipient_alliance_id)');
        $this->addSql('ALTER TABLE stu_user_relations ADD CONSTRAINT FK_E9506D20EEB16BFD FOREIGN KEY (source_user_id) REFERENCES stu_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_user_relations ADD CONSTRAINT FK_E9506D202CDFBA9F FOREIGN KEY (source_alliance_id) REFERENCES stu_alliances (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_user_relations ADD CONSTRAINT FK_E9506D20B15EFB97 FOREIGN KEY (recipient_user_id) REFERENCES stu_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_user_relations ADD CONSTRAINT FK_E9506D20A765B64E FOREIGN KEY (recipient_alliance_id) REFERENCES stu_alliances (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stu_user_relations DROP CONSTRAINT FK_E9506D20EEB16BFD');
        $this->addSql('ALTER TABLE stu_user_relations DROP CONSTRAINT FK_E9506D202CDFBA9F');
        $this->addSql('ALTER TABLE stu_user_relations DROP CONSTRAINT FK_E9506D20B15EFB97');
        $this->addSql('ALTER TABLE stu_user_relations DROP CONSTRAINT FK_E9506D20A765B64E');
        $this->addSql('DROP TABLE stu_user_relations');
    }
}
