<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;


final class Version20250531083843_DatabaseCategoryAward extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add DatabaseCategoryAward';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE stu_database_category_awards (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category_id INT NOT NULL, layer_id INT DEFAULT NULL, award_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_EEBC1A0512469DE2 ON stu_database_category_awards (category_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_EEBC1A053D5282CF ON stu_database_category_awards (award_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_database_category_awards ADD CONSTRAINT FK_EEBC1A0512469DE2 FOREIGN KEY (category_id) REFERENCES stu_database_categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_database_category_awards ADD CONSTRAINT FK_EEBC1A053D5282CF FOREIGN KEY (award_id) REFERENCES stu_award (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_database_categories DROP CONSTRAINT fk_cda2ea6c3d5282cf
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX idx_cda2ea6c3d5282cf
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_database_categories DROP award_id
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_database_category_awards DROP CONSTRAINT FK_EEBC1A0512469DE2
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_database_category_awards DROP CONSTRAINT FK_EEBC1A053D5282CF
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE stu_database_category_awards
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_database_categories ADD award_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_database_categories ADD CONSTRAINT fk_cda2ea6c3d5282cf FOREIGN KEY (award_id) REFERENCES stu_award (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_cda2ea6c3d5282cf ON stu_database_categories (award_id)
        SQL);
    }
}
