<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Override;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;


final class Version20240805154609 extends AbstractMigration
{
    #[Override]
    public function getDescription(): string
    {
        return 'Add LocationMining Entity';
    }

    #[Override]
    public function up(Schema $schema): void
    {

        $this->addSql('CREATE TABLE stu_location_mining (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, location_id INT NOT NULL, commodity_id INT NOT NULL, actual_amount INT NOT NULL, max_amount INT NOT NULL, depleted_at INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AC85C1AC64D218E ON stu_location_mining (location_id)');
        $this->addSql('CREATE INDEX IDX_AC85C1ACB4ACC212 ON stu_location_mining (commodity_id)');
        $this->addSql('ALTER TABLE stu_location_mining ADD CONSTRAINT FK_AC85C1AC64D218E FOREIGN KEY (location_id) REFERENCES stu_location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_location_mining ADD CONSTRAINT FK_AC85C1ACB4ACC212 FOREIGN KEY (commodity_id) REFERENCES stu_commodity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    #[Override]
    public function down(Schema $schema): void
    {

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE stu_location_mining DROP CONSTRAINT FK_AC85C1AC64D218E');
        $this->addSql('ALTER TABLE stu_location_mining DROP CONSTRAINT FK_AC85C1ACB4ACC212');
        $this->addSql('DROP TABLE stu_location_mining');
    }
}
