<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20241205211145_Userreferer extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add User Referer';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE stu_user_referer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, referer TEXT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A00722FDA76ED395 ON stu_user_referer (user_id)');
        $this->addSql('ALTER TABLE stu_user_referer ADD CONSTRAINT FK_A00722FDA76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE stu_user_referer DROP CONSTRAINT FK_A00722FDA76ED395');
        $this->addSql('DROP TABLE stu_user_referer');
    }
}
