<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250113194515_Skill_Enhancement extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add crew skill enhancement table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE stu_skill_enhancement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type SMALLINT NOT NULL, position SMALLINT NOT NULL, expertise INT NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX skill_enhancement_unique_idx ON stu_skill_enhancement (type, position)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE stu_skill_enhancement');
    }
}
