<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260915191823 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stu_orion_auction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start INT NOT NULL, "end" INT NOT NULL, completed_at INT DEFAULT NULL, auction_amount INT NOT NULL, winner_name VARCHAR(255) DEFAULT NULL, image_position SMALLINT NOT NULL, crew_id INT NOT NULL, wanted_commodity_id INT DEFAULT NULL, winner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7AF6695FE259F6 ON stu_orion_auction (crew_id)');
        $this->addSql('CREATE INDEX IDX_7AF669DCBCD0C6 ON stu_orion_auction (wanted_commodity_id)');
        $this->addSql('CREATE INDEX IDX_7AF6695DFCD4B8 ON stu_orion_auction (winner_id)');
        $this->addSql('CREATE TABLE stu_orion_auction_bid (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, max_amount INT NOT NULL, auction_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_252E8C9E57B8F0DE ON stu_orion_auction_bid (auction_id)');
        $this->addSql('CREATE INDEX IDX_252E8C9EA76ED395 ON stu_orion_auction_bid (user_id)');
        $this->addSql('CREATE INDEX orion_auction_bid_auction_idx ON stu_orion_auction_bid (auction_id, max_amount)');
        $this->addSql('ALTER TABLE stu_orion_auction ADD CONSTRAINT FK_7AF6695FE259F6 FOREIGN KEY (crew_id) REFERENCES stu_crew (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_orion_auction ADD CONSTRAINT FK_7AF669DCBCD0C6 FOREIGN KEY (wanted_commodity_id) REFERENCES stu_commodity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_orion_auction ADD CONSTRAINT FK_7AF6695DFCD4B8 FOREIGN KEY (winner_id) REFERENCES stu_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_orion_auction_bid ADD CONSTRAINT FK_252E8C9E57B8F0DE FOREIGN KEY (auction_id) REFERENCES stu_orion_auction (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_orion_auction_bid ADD CONSTRAINT FK_252E8C9EA76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_rump ALTER id DROP IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stu_orion_auction DROP CONSTRAINT FK_7AF6695FE259F6');
        $this->addSql('ALTER TABLE stu_orion_auction DROP CONSTRAINT FK_7AF669DCBCD0C6');
        $this->addSql('ALTER TABLE stu_orion_auction DROP CONSTRAINT FK_7AF6695DFCD4B8');
        $this->addSql('ALTER TABLE stu_orion_auction_bid DROP CONSTRAINT FK_252E8C9E57B8F0DE');
        $this->addSql('ALTER TABLE stu_orion_auction_bid DROP CONSTRAINT FK_252E8C9EA76ED395');
        $this->addSql('DROP TABLE stu_orion_auction');
        $this->addSql('DROP TABLE stu_orion_auction_bid');
        $this->addSql('ALTER TABLE stu_rump ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }
}
