<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260531193945 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stu_ship_log DROP CONSTRAINT fk_74cef0ee1c6af6fd');
        $this->addSql('DROP TABLE stu_ship_log');
        $this->addSql('ALTER TABLE stu_spacecraft_log ADD edited INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stu_ship_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, spacecraft_id INT NOT NULL, text TEXT NOT NULL, date INT NOT NULL, deleted INT DEFAULT NULL, is_private BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_74cef0ee1c6af6fd ON stu_ship_log (spacecraft_id)');
        $this->addSql('ALTER TABLE stu_ship_log ADD CONSTRAINT fk_74cef0ee1c6af6fd FOREIGN KEY (spacecraft_id) REFERENCES stu_spacecraft (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_spacecraft_log DROP edited');
    }
}
