<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122084317 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stu_alliance_job_permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, permission INT NOT NULL, job_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D17D65DBE04EA9 ON stu_alliance_job_permission (job_id)');
        $this->addSql('ALTER TABLE stu_alliance_job_permission ADD CONSTRAINT FK_8D17D65DBE04EA9 FOREIGN KEY (job_id) REFERENCES stu_alliances_jobs (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stu_alliance_job_permission DROP CONSTRAINT FK_8D17D65DBE04EA9');
        $this->addSql('DROP TABLE stu_alliance_job_permission');
    }
}
