<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260906121151 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stu_alliances_relations DROP CONSTRAINT fk_9ebadcd96804fb49');
        $this->addSql('ALTER TABLE stu_alliances_relations DROP CONSTRAINT fk_9ebadcd910a0ea3f');
        $this->addSql('ALTER TABLE stu_user_relations DROP CONSTRAINT fk_e9506d20eeb16bfd');
        $this->addSql('ALTER TABLE stu_user_relations DROP CONSTRAINT fk_e9506d202cdfba9f');
        $this->addSql('ALTER TABLE stu_user_relations DROP CONSTRAINT fk_e9506d20b15efb97');
        $this->addSql('ALTER TABLE stu_user_relations DROP CONSTRAINT fk_e9506d20a765b64e');
        $this->addSql('DROP TABLE stu_alliances_relations');
        $this->addSql('DROP TABLE stu_user_relations');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stu_alliances_relations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type SMALLINT NOT NULL, alliance_id INT NOT NULL, recipient INT NOT NULL, date INT NOT NULL, text TEXT DEFAULT NULL, last_edited INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_9ebadcd910a0ea3f ON stu_alliances_relations (alliance_id)');
        $this->addSql('CREATE INDEX idx_9ebadcd96804fb49 ON stu_alliances_relations (recipient)');
        $this->addSql('CREATE INDEX alliance_relation_idx ON stu_alliances_relations (alliance_id, recipient)');
        $this->addSql('CREATE TABLE stu_user_relations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type SMALLINT NOT NULL, source_user_id INT DEFAULT NULL, source_alliance_id INT DEFAULT NULL, recipient_user_id INT DEFAULT NULL, recipient_alliance_id INT DEFAULT NULL, date INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX user_relation_source_user_idx ON stu_user_relations (source_user_id)');
        $this->addSql('CREATE INDEX user_relation_source_alliance_idx ON stu_user_relations (source_alliance_id)');
        $this->addSql('CREATE INDEX user_relation_recipient_user_idx ON stu_user_relations (recipient_user_id)');
        $this->addSql('CREATE INDEX user_relation_recipient_alliance_idx ON stu_user_relations (recipient_alliance_id)');
        $this->addSql('ALTER TABLE stu_alliances_relations ADD CONSTRAINT fk_9ebadcd96804fb49 FOREIGN KEY (recipient) REFERENCES stu_alliances (id) ON UPDATE RESTRICT ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_alliances_relations ADD CONSTRAINT fk_9ebadcd910a0ea3f FOREIGN KEY (alliance_id) REFERENCES stu_alliances (id) ON UPDATE RESTRICT ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_user_relations ADD CONSTRAINT fk_e9506d20eeb16bfd FOREIGN KEY (source_user_id) REFERENCES stu_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_user_relations ADD CONSTRAINT fk_e9506d202cdfba9f FOREIGN KEY (source_alliance_id) REFERENCES stu_alliances (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_user_relations ADD CONSTRAINT fk_e9506d20b15efb97 FOREIGN KEY (recipient_user_id) REFERENCES stu_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_user_relations ADD CONSTRAINT fk_e9506d20a765b64e FOREIGN KEY (recipient_alliance_id) REFERENCES stu_alliances (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
