<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;


final class Version20250618185937_PIRATEROUND extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds Pirate Round tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE stu_pirate_round (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start INT NOT NULL, end_time INT DEFAULT NULL, max_prestige INT NOT NULL, actual_prestige INT NOT NULL, faction_winner INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE stu_user_pirate_round (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, pirate_round_id INT NOT NULL, destroyed_ships INT NOT NULL, prestige INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_3CECD0A8A76ED395 ON stu_user_pirate_round (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_3CECD0A88DA7A3A1 ON stu_user_pirate_round (pirate_round_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_user_pirate_round ADD CONSTRAINT FK_3CECD0A8A76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_user_pirate_round ADD CONSTRAINT FK_3CECD0A88DA7A3A1 FOREIGN KEY (pirate_round_id) REFERENCES stu_pirate_round (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_user_pirate_round DROP CONSTRAINT FK_3CECD0A8A76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_user_pirate_round DROP CONSTRAINT FK_3CECD0A88DA7A3A1
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE stu_pirate_round
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE stu_user_pirate_round
        SQL);
    }
}
