<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250610150652 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Reset the primary key of crew assignments.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            DROP INDEX crew_assign_crew_idx
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_crew_assign DROP id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_crew_assign ADD PRIMARY KEY (crew_id)
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            DROP INDEX idx_223179_primary
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_crew_assign ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX crew_assign_crew_idx ON stu_crew_assign (crew_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stu_crew_assign ADD PRIMARY KEY (id)
        SQL);
    }
}
