<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;


final class Version20250426182426_ALLIANCE_SETTINGS extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adds the alliance settings table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE stu_alliance_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, alliance_id INT NOT NULL, setting VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_39FF05F710A0EA3F ON stu_alliance_settings (alliance_id)');
        $this->addSql('ALTER TABLE stu_alliance_settings ADD CONSTRAINT FK_39FF05F710A0EA3F FOREIGN KEY (alliance_id) REFERENCES stu_alliances (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE stu_alliance_settings DROP CONSTRAINT FK_39FF05F710A0EA3F');
        $this->addSql('DROP TABLE stu_alliance_settings');
    }
}
