<?php

declare(strict_types=1);

namespace Stu\Migrations\Pgsql;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260531172636 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stu_spacecraft_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, spacecraft_id INT NOT NULL, user_id INT DEFAULT NULL, rump_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, text TEXT NOT NULL, date INT NOT NULL, is_private BOOLEAN NOT NULL, deleted INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX spacecraft_log_spacecraft_idx ON stu_spacecraft_log (spacecraft_id)');
        $this->addSql('CREATE INDEX spacecraft_log_user_idx ON stu_spacecraft_log (user_id)');
        $this->addSql('CREATE TABLE stu_spacecraft_log_scan (spacecraft_id INT NOT NULL, date INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (user_id, spacecraft_id))');
        $this->addSql('CREATE INDEX IDX_FD67BB7BA76ED395 ON stu_spacecraft_log_scan (user_id)');
        $this->addSql('CREATE INDEX spacecraft_log_scan_spacecraft_idx ON stu_spacecraft_log_scan (spacecraft_id)');
        $this->addSql('ALTER TABLE stu_spacecraft_log ADD CONSTRAINT FK_DA27BBBDA76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stu_spacecraft_log_scan ADD CONSTRAINT FK_FD67BB7BA76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stu_spacecraft_log DROP CONSTRAINT FK_DA27BBBDA76ED395');
        $this->addSql('ALTER TABLE stu_spacecraft_log_scan DROP CONSTRAINT FK_FD67BB7BA76ED395');
        $this->addSql('DROP TABLE stu_spacecraft_log');
        $this->addSql('DROP TABLE stu_spacecraft_log_scan');
    }
}
