<?php

declare(strict_types=1);

namespace Stu\Migrations;

use Override;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20241024092428_TutorialRemake extends AbstractMigration
{
    #[Override]
    public function getDescription(): string
    {
        return 'Add new entities for user tutorial remake.';
    }

    #[Override]
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE stu_tutorial_step (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, module VARCHAR(50) NOT NULL, view VARCHAR(100) NOT NULL, next_step_id INT DEFAULT NULL, title TEXT DEFAULT NULL, text TEXT DEFAULT NULL, elementIds TEXT DEFAULT NULL, innerUpdate TEXT DEFAULT NULL, fallbackIndex INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX tutorial_view_idx ON stu_tutorial_step (module, view)');
        $this->addSql('CREATE TABLE stu_user_tutorial (user_id INT NOT NULL, tutorial_step_id INT NOT NULL, PRIMARY KEY(user_id, tutorial_step_id))');
        $this->addSql('CREATE INDEX IDX_9840DDF3A76ED395 ON stu_user_tutorial (user_id)');
        $this->addSql('CREATE INDEX IDX_9840DDF3D356979 ON stu_user_tutorial (tutorial_step_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_82D9BF6BB13C343E ON stu_tutorial_step (next_step_id)');
        $this->addSql('ALTER TABLE stu_user_tutorial ADD CONSTRAINT FK_9840DDF3A76ED395 FOREIGN KEY (user_id) REFERENCES stu_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_user_tutorial ADD CONSTRAINT FK_9840DDF3D356979 FOREIGN KEY (tutorial_step_id) REFERENCES stu_tutorial_step (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stu_tutorial_step ADD CONSTRAINT FK_82D9BF6BB13C343E FOREIGN KEY (next_step_id) REFERENCES stu_tutorial_step (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    #[Override]
    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE stu_user_tutorial DROP CONSTRAINT FK_9840DDF3A76ED395');
        $this->addSql('ALTER TABLE stu_user_tutorial DROP CONSTRAINT FK_9840DDF3D356979');
        $this->addSql('ALTER TABLE stu_tutorial_step DROP CONSTRAINT FK_82D9BF6BB13C343E');
        $this->addSql('DROP TABLE stu_tutorial_step');
        $this->addSql('DROP TABLE stu_user_tutorial');
    }
}
